FROM arm32v7/python:latest

# See https://github.com/waveform80/picamera/issues/578
ENV READTHEDOCS=True

WORKDIR /code

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
RUN usermod -a -G video root

sudo apt-get -y purge wolfram-engine
2
sudo apt-get -y purge libreoffice*
3
sudo apt-get -y clean
4
sudo apt-get -y autoremove
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get -y install python3 python3-dev python3-pip
RUN apt-get install libatlas-base-dev -y
RUN pip install --upgrade pip setuptools wheel
RUN apt-get -y install git build-essential cmake pkg-config
RUN apt-get -y install libjpeg-dev libpng-dev libtiff-dev
RUN apt-get -y install libprotobuf-dev protobuf-compiler
RUN apt-get -y install libv4l-dev
#RUN apt-get install libjasper-dev
RUN apt-get install libqtgui4 -y
RUN apt-get install libqt4-test -y
RUN apt-get install libhdf5-dev -y

COPY requirements.txt .
RUN pip3 install -r requirements.txt

EXPOSE 5000
COPY . .

CMD ["python", "./main.py"]
